-- MySQL Script generated by MySQL Workbench
-- Sun Nov 19 20:56:56 2023
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `userID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
   UNIQUE KEY unique_username (username),
   UNIQUE KEY unique_email (email))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hotels` (
  `hotelID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`hotelID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reviews` (
  `reviewID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `hotelID` VARCHAR(50) NOT NULL,
  `hotelName` VARCHAR(50) NOT NULL DEFAULT 'Hotel',
  `rating` INT NULL,
  `comment` TEXT NULL,
  `reviewDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `clean` BOOLEAN DEFAULT FALSE,
  `petFriendly` BOOLEAN DEFAULT FALSE,
  `ecoFriendly` BOOLEAN DEFAULT FALSE,
  `excellentService` BOOLEAN DEFAULT FALSE,
  `dirty` BOOLEAN DEFAULT FALSE,
  `missingAmenities` BOOLEAN DEFAULT FALSE,
  `hiddenFees` BOOLEAN DEFAULT FALSE,
  `poorService` BOOLEAN DEFAULT FALSE,
  
  PRIMARY KEY (`reviewID`),
  FOREIGN KEY (`userID`) REFERENCES `users`(`userID`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;